-- Custom defines for IPE:
NDefines.NDiplomacy.HEGEMONY_LOST_DAYS = 1825 -- from 7300, to make losing hegemony less painful
NDefines.NDiplomacy.CHANGE_RIVAL_YEARS = 5 -- from 25, to allow rivals to be switched much more frequently
NDefines.NDiplomacy.CONDOTTIERI_MIN_DURATION = 36 -- from 18, to nerf condottieri
NDefines.NDiplomacy.NUM_POSSIBLE_RIVALS = 2 -- from 3, to make AI diplomacy more flexible
NDefines.NDiplomacy.MAX_FREE_CITIES = 30 -- from 12, to compensate for new free cities
NDefines.NDiplomacy.HRE_PRINCE_AUTHORITY_THRESHOLD = 30	-- from 25, to compensate for new princes
NDefines.NDiplomacy.IMPERIAL_AUTHORITY_FROM_PRINCES = 0.05 -- Scales to threshold
NDefines.NDiplomacy.IMPERIAL_REFORM_COST = 75
NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_MIN_VALUE = 100 -- from 80, to nerf the Emperor of China
NDefines.NDiplomacy.SCALED_TRUCE_YEARS = 5 -- 15-year truce timers are ridiculous
NDefines.NDiplomacy.HRE_VOTE_TOO_SMALL = -250 -- from -25, to prevent weak HRE princes from becoming Emperor
NDefines.NDiplomacy.AE_SAME_CULTURE = 3 -- from 0.5
NDefines.NDiplomacy.AE_SAME_CULTURE_GROUP = 3 -- from 0.25
NDefines.NDiplomacy.AE_INFIDEL_CONQUEST = 0.5 -- from 0.25
NDefines.NDiplomacy.AE_SAME_RELIGION = 1 -- from 0.5
NDefines.NDiplomacy.AE_SAME_RELIGION_GROUP = 0.5 -- from 0
NDefines.NDiplomacy.AE_SAME_OVERLORD = 1 -- from 0.5
NDefines.NDiplomacy.AE_PROVINCE_CAP = 10 -- from 30, to allow faster expansion into provinces with high development
NDefines.NDiplomacy.PO_DEMAND_PROVINCES_AE = 0.375 -- from 0.75
NDefines.NDiplomacy.PO_RETURN_CORES_AE = 0.1 -- from 0.5
NDefines.NDiplomacy.PO_BECOME_VASSAL_AE = 0.25 -- from 0.5
NDefines.NDiplomacy.PO_TRANSFER_VASSAL_AE = 0.25 -- from 0.33
NDefines.NDiplomacy.PEACE_COST_DEMAND_PROVINCE = 0.75 -- from 1, to allow nations to take more land in development-rich regions
NDefines.NDiplomacy.PEACE_COST_CONCEDE_PROVINCE = 0.75 -- from 1, to allow nations to take more land in development-rich regions
NDefines.NDiplomacy.PEACE_COST_BECOME_VASSAL = 0.75	-- from 1, to allow nations to take more land in development-rich regions
NDefines.NDiplomacy.PEACE_COST_RETURN_CORE = 0.1 -- from 1, to incentivize reconquest and make it faster
NDefines.NDiplomacy.PEACE_COST_REVOKE_CORE = 0.75 -- from 1
NDefines.NDiplomacy.PEACE_COST_RELEASE_ANNEXED = 0.75 -- from 1
NDefines.NDiplomacy.ANNEX_DIP_COST_PER_DEVELOPMENT = 4 -- from 8
NDefines.NDiplomacy.INTEGRATE_VASSAL_MIN_YEARS = 0 -- from 10
NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 12 -- from 60, helps prevent AI border gore
NDefines.NDiplomacy.MINIMUM_TRADE_POWER_TO_PREVENT_PRIVATEER = 0.05 -- to allow more nations to stop privateering through war
NDefines.NDiplomacy.MINIMUM_TRADE_POWER_SHARE_FOR_PRIVATEER_OPINION_HIT = 0.05 -- to make privateering more diplomatically penalizing
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_STATE_WITH_PROSPERITY = 0.01 -- from 0.03, because China has a lot of states now
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_DEVASTATION = -1 -- from -10, to fit with the new development system
NDefines.NDiplomacy.NUM_OF_GREAT_POWERS = 16 -- from 8, to compensate for the high number of powerful nations
NDefines.NDiplomacy.TRIBUTE_MAX_MONARCH_POWER = 6 -- from 12, to nerf the Emperor of China
NDefines.NDiplomacy.AUTODIPLO_TARGET_NEIGHBOURS_HOPELESS_LIMIT = -100 -- from -150, to prevent diplomats from trying to improve relations with rivals

NDefines.NCountry.EXPLOIT_COOLDOWN_MONTHS = 120 -- from 240, to make development manipulation more flexible
NDefines.NCountry.MONTHS_FOR_MAX_MP_ALERT = 6 -- from 3, to make monarch points easier to manage
NDefines.NCountry.INSTITUTION_BONUS_FROM_IMP_DEVELOPMENT = 0 -- from 5, institutions can no longer be spread by developing
NDefines.NCountry.INSTITUTION_CAP_IMP_DEVELOPMENT = 0 -- from 10, institutions can no longer be spread by developing
NDefines.NCountry.INSTITUTION_BASE_IMP_DEVELOPMENT = 0 -- from 30, institutions can no longer be spread by developing
NDefines.NCountry.MAXIMUM_CONDOTTIERI = 10 -- from 20, to nerf condottieri in MP
NDefines.NCountry.CORRUPTION_COST = 0.1	-- from 0.05
NDefines.NCountry.ESTATE_MIN_DISTRIBUTED_CROWNLAND = 30.003 -- from 30, to fix 29.998% error
NDefines.NCountry.ESTATE_CROWNLAND_FROM_DEV = 0 -- from 0.2, so that natural development growth doesn't increase crownland
NDefines.NCountry.MIN_DEV_FOR_FREE_CITY = 5	-- from 10, because many Free Cities have less than 10 development
NDefines.NCountry.MIN_DEVELOPMENT_FOR_GOV_RANK_2 = 500 -- from 300, to get in the way of Burgundy
NDefines.NCountry.MIN_DEVELOPMENT_FOR_GOV_RANK_3 = 2500	-- from 1000, to stop countries from reaching empire rank too quickly
NDefines.NCountry.PARLIAMENT_PRESTIGE_HIT = -50 -- from -20, to nerf Parliament
NDefines.NCountry.GREAT_PROJECT_MANPOWER_REQUIRED_FOR_CONSTRUCTION_BOOST = 25000 -- from 10000
NDefines.NCountry.GREAT_PROJECT_MANPOWER_CONSTRUCTION_BOOST_AMOUNT_IN_DAYS = 365 -- from 730
NDefines.NCountry.GREAT_PROJECT_MONEY_REQUIRED_FOR_CONSTRUCTION_BOOST = 500 -- from 250
NDefines.NCountry.GREAT_PROJECT_MONEY_CONSTRUCTION_BOOST_AMOUNT_IN_DAYS = 365 -- from 730
NDefines.NCountry.LAND_FORCELIMIT_EXTRA_COST_FACTOR = 3	-- from 2, to stop rich countries from turning wealth into exponential military strength
NDefines.NCountry.NAVAL_FORCELIMIT_EXTRA_COST_FACTOR = 3 -- from 2, to stop rich countries from turning wealth into exponential military strength
NDefines.NCountry.PIETY_PERCENTAGE_AT_NEW_RULER = 0.5 -- from 0.25, to make it easier to maintain high mysticism or legalism
NDefines.NCountry.PIETY_INCREASE_AT_GOOD_WAR = 0 -- from 0.25, so that declaring wars no longer affects piety
NDefines.NCountry.PIETY_DECREASE_AT_BAD_WAR = 0 -- from -0.33, so that declaring wars no longer affects piety
NDefines.NCountry.MONARCH_DEATH = 2 -- from 4, to produce slightly longer monarch lifespans
NDefines.NCountry.FREE_IDEA_GROUP_COST = 4 -- from 3, because two idea groups are unlocked at once in Dei Gratia
NDefines.NCountry.PS_BUY_NATIVE_ADVANCEMENT = 600 -- from 500
NDefines.NCountry.PS_ADD_TRIBAL_LAND_EXTRA_COST_PER_PROVINCE = 100
NDefines.NCountry.PS_IMPROVE_PROVINCE_BASE = 100 -- from 50, to fit the new development system
NDefines.NCountry.PS_SCORCH_EARTH = 10 -- from 5
NDefines.NCountry.CORE_HAD_PERMANENT_CLAIM = 0.5 -- from 0.25, to further incentivize the following of mission trees and reduce the use of admin points
NDefines.NCountry.CORE_LOSE = 100 -- from 50, to prevent tags disappearing from the map prematurely
NDefines.NCountry.CORE_LOSE_CULTURE_GROUP = 250 -- from 150, to prevent tags disappearing from the map prematurely
NDefines.NCountry.MAX_NATIONALISM = 100 -- from 10, to make it so that separatism can last up to 200 years
NDefines.NCountry.YEARS_OF_NATIONALISM = 100 -- from 30, to make unrest from conquests persist for a very long time
NDefines.NCountry.REGULAR_COLONY_GROWTH = 10 -- from 25, to slow down colonization
NDefines.NCountry.COLONIAL_CLAIM_BONUS = 50 -- from 10, to encourage the Iberian colonizers to stay Catholic
NDefines.NCountry.COLONIAL_CLAIM_VIOLATION = -25 -- from -20, to partially counteract the benefits of the Treaty of Tordesillas
NDefines.NCountry.COLONY_VIOLATION_PAPAL_INFLUENCE_COST = -5 -- from -10, to make violation of the Treaty of Tordesillas less punishing religiously
NDefines.NCountry.OVEREXTENSION_FACTOR = 0.25 -- from 1.0, to allow countries to take more land
NDefines.NCountry.OVEREXTENSION_OVERSEAS_FACTOR = 0.125 -- from 0.5, to reflect the change in overextension overall
NDefines.NCountry.RELEASED_NATION_ARMY_SIZE = 0.8 -- from 0.5, to make it easier for recently released nations to survive
NDefines.NCountry.MIGRATION_COOLDOWN = 120 -- from 60
NDefines.NCountry.BASE_TARIFF = 0.25 -- from 0.10, to buff colonial nations so that they are more comparable to trade companies
NDefines.NCountry.TARIFF_LIBERTY_INCREASE = 0.5	-- from 1.0, to account for higher tariffs
NDefines.NCountry.LIBERTY_DESIRE_TRUST = -1	-- from -0.4
NDefines.NCountry.LIBERTY_DESIRE_DIPLOMATIC_REPUTATION = -5 -- from -3
NDefines.NCountry.MIN_LIBERTY_DESIRE_INFLUENCE = -1000 -- from -100, because it's very easy to reach -100 with very intensive developing
NDefines.NCountry.CONCENTRATE_DEVELOPMENT_DEVELOPMENT_DECREASE = 0 -- from 0.2, to disable concentrate development
NDefines.NCountry.RAZE_PROVINCE_DEVELOPMENT_DECREASE = 0.2 -- from 0.33, to better fit the new development system
NDefines.NCountry.DEBT_LIMIT_ADM = -100000	-- from -100, because why not
NDefines.NCountry.DEBT_LIMIT_DIP = -100000	-- diplomatically annexing Ming at game start would cost over 54,000 diplomatic points
NDefines.NCountry.DEBT_LIMIT_MIL = -100000	-- from -100, because why not
NDefines.NCountry.BREAK_ALLIANCE_REQUIRED_OPINION = 1000
NDefines.NCountry.RETURN_CORE_REQUIRED_OPINION = 1000
NDefines.NCountry.REDUCE_OPINION_REQUIRED_OPINION = 1000
NDefines.NCountry.TRADE_FAVORS_FOR_GOLD_FAVOR_COST = 50
NDefines.NCountry.TRADE_FAVORS_FOR_GOLD_REQUIRED_OPINION = 1000
NDefines.NCountry.TRADE_FAVORS_FOR_MEN_FAVOR_COST = 50
NDefines.NCountry.TRADE_FAVORS_FOR_MEN_REQUIRED_OPINION = 1000
NDefines.NCountry.TRADE_FAVORS_FOR_SAILORS_FAVOR_COST = 50
NDefines.NCountry.TRADE_FAVORS_FOR_SAILORS_REQUIRED_OPINION = 1000
NDefines.NCountry.TRADE_FAVORS_FOR_HEIR_FAVOR_COST = 100
NDefines.NCountry.TRADE_FAVORS_FOR_HEIR_REQUIRED_OPINION = 1000
NDefines.NCountry.TRADE_FAVORS_FOR_TRUST_REQUIRED_OPINION = 100
NDefines.NCountry.TRADE_FAVORS_FOR_WAR_PREP_REQUIRED_OPINION = 100
NDefines.NCountry.USING_FAVORS_AI_BOOST = 0
NDefines.NCountry.REVOLUTION_EMBRACE_MIN_SPREAD = 0.5 -- from 1, to make embracing the Revolution easier
NDefines.NCountry.TRIBE_STARTING_DEV = 0 -- from 3
NDefines.NCountry.MIGRATORY_TRIBE_DEVELOPMENT_PROGRESS = 0 -- from 0.02
NDefines.NCountry.MIGRATORY_TRIBE_DEVELOPMENT_OTHER_BONUS = 0 -- from 0.08
NDefines.NCountry.TRIBE_MIGRATION_MIL_COST = 100
NDefines.NCountry.EXPAND_INFRASTRUCTURE_DEV_LIMIT = 50 -- from 15, to prevent need to spam it

NDefines.NEconomy.EDICTS_COST_INCREASE = 1.0 -- from 2.0, to make edicts cheaper
NDefines.NEconomy.MAX_DIPLO_LOAN_INTEREST = 10 -- from 100, to prevent an exploit with diplomatic loans that can allow you to accrue infinite money
NDefines.NEconomy.DEBASE_MAX_STORED_MONTHS = 600 -- Debase currency stores up to this many months of charges.
NDefines.NEconomy.DEBASE_MONTHS_PER_CHARGE = 120 -- Amount of months used for one debase charge.
NDefines.NEconomy.DEBASE_ADDED_CORRUPTION = 5 -- This amount of corruption added per standard sized bank loan worth of currency.
NDefines.NEconomy.DECREASE_AUTONOMY_STEP = -10 -- from -25, to nerf decreasing autonomy
NDefines.NEconomy.LAND_TECH_MAINTENANCE_IMPACT = 0.04 -- from 0.02, to prevent infinite money
NDefines.NEconomy.LAND_TECH_MERC_MAINTENANCE_IMPACT = 0.12 -- from 0.08, to prevent infinite money
NDefines.NEconomy.BANKRUPTCY_BUILDING_DESTRUCTION_THRESHOLD = 10 -- from 5, to eliminate bankruptcy building as a viable strategy
NDefines.NEconomy.BANKRUPTCY_PROVINCE_DEVASTATION_GAIN = 20 -- from 10, to make bankruptcy *really* hurt
NDefines.NEconomy.TRADE_WIND_STRENGTH = 0.1 -- from 0.5, to prevent Portugal from reaching Guyana in 1445
NDefines.NEconomy.TRADED_FRACTION_FOR_BONUS = 0.10 -- from 0.20, which is hard to achieve with India and China
NDefines.NEconomy.MERCHANT_MAX_POWER_BONUS = 0.5 -- from 2, to stop the power of German merchant spam
NDefines.NEconomy.PIRATES_TRADE_POWER_FACTOR = 1 -- from 1.5, to nerf privateering and pirate republics
NDefines.NEconomy.PIRATES_MONOPOLY_BONUS = 0 -- from 1, to nerf privateering and pirate republics
NDefines.NEconomy.CARAVAN_FACTOR = 20 -- from 3, to greatly lower the amount of caravan power small nations can acquire

NDefines.NMilitary.SLACKEN_MANPOWER_INCREASE = 1 -- from 2, to shorten wars by reducing the reservoir of manpower
NDefines.NMilitary.ARMY_DRILL_YEARLY_DECAY = -1.0 -- from 2.5, to make drilling a more important element of war strategy
NDefines.NMilitary.ARMY_DRILL_YEARLY_GAIN = 20.0 -- from 10.0, to make drilling a more important element of war strategy
NDefines.NMilitary.ARMY_DRILL_SKILL_MONTHS = 60 -- from 120, to increase the probability generals improve skill from drilling
NDefines.NMilitary.BANNER_REINFORCE_SPEED = 0 -- from -0.5, to make banners viable for use in combat
NDefines.NMilitary.MARINE_SHOCK_DAMAGE_TAKEN = 0 -- from 0.25, to make marines actually usable and not a feature no one will ever use
NDefines.NMilitary.BANNER_MANPOWER_USAGE = 0.5 -- from 0.25, to keep a small nerf to banners after buffing them
NDefines.NMilitary.BANNER_REINFORCE_SPEED = 0 -- from -0.5, to make banners not useless
NDefines.NMilitary.BANNER_MAINTENANCE_COST = 1 -- from 0.5, to keep a small nerf to banners after buffing them
NDefines.NMilitary.FORT_DEVASTATION_IMPACT = -2.5 -- from -10, to balance with plagues
NDefines.NMilitary.FORT_PER_DEV_RATIO = 25	-- from 50, to discourage AI from deleting forts
NDefines.NMilitary.ART_REGIMENT_MANPOWER_COST = 0.25 -- from 1, so that artillery regiments have 250 men each (10,000 men in a 40-width backrow)
NDefines.NMilitary.MIN_MONTHLY_MANPOWER = 0.25 -- from 0.1, to compensate for higher attrition in the mod
NDefines.NMilitary.MIN_MONTHLY_SAILORS = 25 -- from 5, to allow smaller nations to do more naval operations
NDefines.NMilitary.HEAVY_SHIP_COST = 100 -- from 50, to stop heavy ship spam
NDefines.NMilitary.FORTRESS_COST = 0.25 -- from 0.5, forts too expensive for large nations
NDefines.NMilitary.LIGHT_SHIP_COST = 10	-- from 20
NDefines.NMilitary.GALLEY_COST = 20	-- from 10
NDefines.NMilitary.TRANSPORT_COST = 10 -- from 12
NDefines.NMilitary.MERCENARY_REINFORCE_COST_MULTIPLIER = -0.5 -- from -1.0, so that mercenary reinforcement is not free
NDefines.NMilitary.TRADITION_GAIN_NAVAL = 20 -- from 40, to decrease discrepancies in navy tradition
NDefines.NMilitary.LOOT_DEVASTATION_IMPACT = 9 -- from 10
NDefines.NMilitary.SCORCHED_DURATION = 24 -- months
NDefines.NMilitary.NOMAD_PLAINS_SHOCK_BONUS = 0.1 -- from 0.25, to compensate for the lack of a penalty now		
NDefines.NMilitary.NOMAD_NON_PLAINS_SHOCK_PENALTY = 0 -- from -0.25, because hordes often led successful mountain campaigns
NDefines.NMilitary.DEFAULT_WARGOAL_BATTLESCORE_BONUS = 10 -- from 3, to lessen the influence of sieges on warscore
NDefines.NMilitary.DAYS_PER_PHASE = 3 -- from 3, to dramatically increase realism of battles
NDefines.NMilitary.SUPPLY_DEPOT_MIL_COST = 10	-- from 20, to encourage the building of supply depots
NDefines.NMilitary.CREATE_JANISSARIES_MIL_COST = 5	-- from 10, so Ottomans can spend fewer military points on Janissaries
NDefines.NMilitary.RAJPUT_BASE_COST_MODIFIER = 1
NDefines.NMilitary.COSSACK_BASE_COST_MODIFIER = 1 -- Cossacks shouldn't be so expensive
NDefines.NMilitary.FLAGSHIP_REQUIRED_NAVY_SIZE_IN_SAILORS = 1000 -- from 1500
NDefines.NMilitary.FLAGSHIP_COST_DUCATS = 200 -- from 100, to correlate with the new cost of heavy ships
NDefines.NMilitary.MERCENARY_COMPANY_MAX_REGIMENTS = 10	-- from 60, to reduce the size of mercenary companies
NDefines.NMilitary.NAVAL_BASE_DISENGAGEMENT_CHANCE = 0.5 -- from 0.1, to make ships more likely to retreat at low morale
NDefines.NMilitary.LEADER_WORK_YEARS_DEATH_FACTOR = 5 -- from 2, to decrease the chance that leaders die
NDefines.NMilitary.LEADER_AGE_DEATH_FACTOR = 5 -- from 3, to decrease the chance that leaders die
NDefines.NMilitary.MERCENARY_COMPANY_ARMY_TRADITION = 0	-- from 50, to make mercenary company generals irrelevant

NDefines.NAI.ACCEPTABLE_BALANCE_DEFAULT = 1.3 -- from 1.7, to encourage AI to be more aggressive in pursuing battle
NDefines.NAI.EDICT_VALUE_THRESHOLD = 20 -- from 120, to encourage the AI to use edicts
NDefines.NAI.DIPLOMATIC_ACTION_GUARANTEE_POWERBALANCE_FACTOR = 20 -- from 80, because AI is too aggressive with guarantees
NDefines.NAI.MIN_INCOME_FOR_SUBSIDIES = 50 -- from 20, to prevent poorer AI from spending money on subsidies
NDefines.NAI.AGGRESSIVENESS = 25 -- from 200, because base AI aggressiveness is too high and results in too many wars
NDefines.NAI.AGGRESSIVENESS_BONUS_EASY_WAR = 25 -- from 300, because base AI aggressiveness is too high and results in too many wars
NDefines.NAI.BIGSHIP_FRACTION = 0.2	-- from 0.4, because heavies are expensive
NDefines.NAI.ARTILLERY_FRACTION = 0.2 -- Ratio of artillery to infantry AI will build
NDefines.NAI.INCOME_SAVINGS_FRACTION = 0.5 -- AI will reserve this amount of their surplus for long-term savings
NDefines.NAI.ARMY_BUDGET_FRACTION = 0.6 -- from 0.7
NDefines.NAI.NAVY_BUDGET_FRACTION = 0.4 -- from 0.5
NDefines.NAI.FORT_BUDGET_FRACTION = 0.8 -- from 0.4, to make AI stop deleting forts
NDefines.NAI.DIPLOMATIC_INTEREST_DISTANCE = 100 -- from 150, to prevent AI from making stupid alliances
NDefines.NAI.CALL_IN_ALLIES_POWER_RATIO = 2.5 -- from 4
NDefines.NAI.REVOLUTION_EMBRACE_MAX_ABSOLUTISM = 50 -- from 35, to make it rarer for AI to embrace the Revolution
NDefines.NAI.DEVELOPMENT_CAP_BASE = 50 -- from 10, to encourage AI development
NDefines.NAI.PEACE_HIGH_WAR_EXHAUSTION_THRESHOLD = 5 -- from 10, because Ming is stupid
NDefines.NAI.PEACE_STALLED_WAR_THRESHOLD = 5 -- from 3, to encourage AI to seek faster peaces
NDefines.NAI.PEACE_WAR_EXHAUSTION_FACTOR = 10 -- from 2
NDefines.NAI.PEACE_ALLY_WAR_DIRECTION_MULT = 0.5 -- from 0
NDefines.NAI.PEACE_DESPERATION_FACTOR = 80 -- from 40, because Ming is stupid
NDefines.NAI.PEACE_REBELS_FACTOR = 40 -- from 20, because Ming is stupid
NDefines.NAI.PEACE_ALLY_FORCE_BALANCE_MULT = 0.5 -- from 0
NDefines.NAI.PEACE_ALLY_MILITARY_STRENGTH_MULT = 1
NDefines.NAI.PEACE_OTHER_WAR_FORCE_BALANCE_MULT = 0.33
NDefines.NAI.PEACE_CALL_FOR_PEACE_FACTOR = 10 -- from 3, to encourage AI to end long-winded wars
NDefines.NAI.PEACE_MANDATE_THREAT_FACTOR = 1 -- so Ming stops death warring Oirat
NDefines.NAI.PEACE_TERMS_REVOKE_ELECTOR_BASE_MULT = 10000.0
NDefines.NAI.PEACE_TERMS_INDEPENDENCE_BASE_MULT = 10000.0
NDefines.NAI.PEACE_TERMS_UNION_BASE_MULT = 10000.0
NDefines.NAI.PEACE_TERMS_VASSAL_BASE_MULT = 10000.0
NDefines.NAI.PEACE_TERMS_TAKE_MANDATE_BASE_MULT = 10000.0
NDefines.NAI.PEACE_TERMS_CHANGE_GOVERNMENT_BASE_MULT = 100 -- from 0.75, so AI will actually change governments
NDefines.NAI.PEACE_TERMS_PILLAGE_CAPITAL_MULT = 0 -- from 2.0, so AI will never do it
NDefines.NAI.PEACE_TERMS_DISMANTLE_REVOLUTION_BASE_MULT = 10000.0
NDefines.NAI.PEACE_TERMS_CHANGE_HRE_RELIGION_BASE_MULT = 10000.0
NDefines.NAI.PEACE_TERMS_ENFORCE_REBEL_DEMANDS_BASE_MULT = 10000.0
NDefines.NAI.PEACE_TERMS_PROVINCE_NO_CB_MULT = 0.1 -- from 0.5, to discourage AI from taking provinces that cost excessive warscore
NDefines.NAI.PEACE_TERMS_PROVINCE_CORE_MULT = 100 -- from 3, to make the AI value the reconquest of its own cores
NDefines.NAI.PEACE_TERMS_PROVINCE_WARGOAL_MULT = 30 -- from 2
NDefines.NAI.PEACE_TERMS_PROVINCE_CLAIM_MULT = 30 -- AI desire for a province is multiplied by this if it has a claim on it
NDefines.NAI.PEACE_TERMS_RETURN_CORES_VASSAL_MULT = 30 -- from 2, to compensate for AI's reduced desire to give provinces to vassals
NDefines.NAI.PEACE_TERMS_RETURN_CORES_NOT_FRIEND_MULT = 0 -- from 0.75, to stop border gore
NDefines.NAI.PEACE_TERMS_RETURN_CORES_IMPERIAL_LIBERATION_MULT = 100 -- from 2.0
NDefines.NAI.PEACE_TERMS_RELEASE_ANNEXED_HRE_MULT = 3 -- from 2, to encourage releasing of nations in the HRE
NDefines.NAI.PEACE_TERMS_PROVINCE_VASSAL_MULT = 0.1 -- AI desire for a province is multiplied by this if it would go to their vassal instead of themselves
NDefines.NAI.PEACE_TERMS_PROVINCE_NOT_ADJACENT_MULT = 0.25 -- from 0.5, to stop border gore
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_BASE_FACTOR = 40 -- from 25, to encourage the AI to fabricate claims
NDefines.NAI.AI_WANT_ACCEPT_CULTURES = 300 -- from 100, to increase the AI's desire for accepted culture provinces
NDefines.NAI.INVADING_BRAVERY = 0.75 -- from 1, to discourage the AI from performing inadequate naval invasions
NDefines.NAI.INVADING_MAX_AWAY_RATIO = 0.5 -- from 0.45, to encourage the AI to perform large-scale naval invasions
NDefines.NAI.ADVISOR_PROMOTION_AGE_CUTOFF = 45 -- from 40, to encourage the AI to promote advisors
NDefines.NAI.ARMY_DISTANCE_SCORE_IMPACT = 1
NDefines.NAI.BORDER_DISTANCE_SCORE_IMPACT = 25
NDefines.NAI.IMPORANT_PROVINCE_THRESHOLD = 0.025 -- from 0.05, to encourage the AI to defend its own provinces
NDefines.NAI.REGION_PLANNING_HOMELAND_PRIORIZATION = 10 -- from 5.1, to encourage the AI to defend its own provinces
NDefines.NAI.REPAY_LOAN_BASE_AI_DESIRE = 10	-- from 5, to make AI more likely to repay loans
NDefines.NAI.ESTATE_PRIVILEGE_GRANT_THRESHOLD = 7.5 -- from 9.9
NDefines.NAI.ESTATE_MAX_WANTED_INFLUENCE = 85 -- from 73, to make AI less bad at estate management
NDefines.NAI.ESTATE_MAX_PRIVILEDGES = 4 -- from 2, to make AI less bad at estate management

NDefines.NAIEconomy.REBEL_THREAT_MILITARIZE_THRESHOLD = 0.9	-- from 0.8
NDefines.NAIEconomy.MILITARY_FOCUS_UPPER_BOUND = 3.0 -- from 2.0
NDefines.NAIEconomy.LOAN_REPAYMENT_SAVINGS_PRIORITY = 1.5 -- from 0.1

NDefines.NReligion.MAX_CHRISTIAN_RELIGIOUS_CENTERS = 7 -- from 3, to make the Protestant Reformation more difficult to stamp out immediately
NDefines.NReligion.YEARLY_PAPAL_INFLUENCE_CATHOLIC = 1 -- from 0.5, to make the following of the Catholic religion more viable
NDefines.NReligion.REFORM_DESIRE_PER_YEAR = 0.005 -- from 0.002

NDefines.NGovernment.GOVERNMENT_REFORM_COST_CENTRALIZE_STATE = 100000
NDefines.NGovernment.CENTRALIZE_STATE_REDUCTION = 0
NDefines.NGovernment.CENTRALIZE_STATE_YEARS = 1000